version: '3.8'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:postgresql://mesadigital-vendas-pg:5433/
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: secret

services:
  banco-vendas:
    image: postgres:15.4-alpine
    container_name: mesadigital-vendas
    ports:
      - "5433:5433"
    command: [ "postgres", "-c", "port=5433" ]
    volumes:
      - "mesadigital-vendas-pg-volume:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - mesadigital-vendas-network
    environment:
      <<: *database-variables

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped


networks:
  mesadigital-vendas-network:
    driver: bridge

volumes:
  mesadigital-vendas-pg-volume:
  redis-data: