server:
  port: 8081
  error:
    include-stacktrace: never

spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  application:
    name: operacoes
  kafka:
    bootstrap-servers: localhost:9093
  datasource:
    url: jdbc:postgresql://localhost:5433/vendas
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
    hikari:
      username: postgres
      password: secret
      driver-class-name: org.postgresql.Driver
      liquibase:
        enabled: false
        change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        boot:
          allow_jdbc_metadata_access: false
    generate-ddl: true
    show-sql: false

mesadigital:
  urlcaixa: /caixas
  urlBase: http://localhost:8082